import "./globals.css";
import Header from "./components/Header";
import Providers from "./redux/Provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">      
      <body>
        <Providers>
        <div>
          <Header/>
          {children}
        </div>    
        </Providers>    
      </body>
    </html>
  );
}
